export const ADDITION_MODE = 'ADDITION_MODE';
export const SUBTRACTION_MODE = 'SUBTRACTION_MODE';
export const MULTIPLICATION_MODE = 'MULTIPLICATION_MODE';
export const DIVISION_MODE = 'DIVISIONMODE_MODE';